### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by MartinRyx** [pe-st/garmin-connect-export#43]
When trying to use the script i get the following error:
```
Welcome to Garmin Connect Exporter!
[ERROR] Failed to reach url https://sso.garmin.com/sso/signin?service...(url shortened)
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)>
```

When I try to open the URL in a browser I get to a login page.

## Traceback
```
Connecting to Garmin Connect...Traceback (most recent call last):
  File "C:\Users\marti\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\marti\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 946, in send
    self.connect()
  File "C:\Users\marti\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1409, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\marti\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\marti\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\marti\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)
```

**Comment by pe-st** [comment]
Hello @MartinRyx 
I can't reproduce the issue with my setup (I just checked with Python 3.8.2 on macOS).

But there are other people having observed the same or a similar issue, see https://github.com/pe-st/garmin-connect-export/issues/40.

They mentioned a script `Install Certificates` that comes with some Python installation, maybe you have got this script with your Python version and it could help?

Regards, Peter

**Comment by telemaxx** [comment]
python 3.6.4rc1 on windows10 is also ok

**Comment by MartinRyx** [comment]
> python 3.6.4rc1 on windows10 is also ok

@telemaxx I tried Python 3.8.3 on windows 10

**Comment by telemaxx** [comment]
now i updated to 3.8.3 and still working.
installed from here:
https://www.python.org/downloads/release/python-383/
"Windows x86 executable installer"
than i did the "custom installation" and selected "for all users"
