### ISSUE TITLE
[ERROR] Failed to reach url http://connect.garmin.com/proxy/download-service/files/activity/5321283197, error: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by pierretamisier** [pe-st/garmin-connect-export#44]
I started using the gcexport.py script again last week (after the Garmin ransomware problem) following ~3 months not using it.  Now it seems the gcexport.py keeps throwing an error 400 when downloading the tcx.

```
pierre@pierre-thinkpad:~$ python ~/Workspace/garmin-connect-export/gcexport.py -d ~/GarminConnect -c 10 -f original -u --username myemail@mail.com --password mypassword --originaltime --desc && rm ~/GarminConnect/*.json
Welcome to Garmin Connect Exporter!
[WARNING] Output directory /home/pierre/GarminConnect already exists. Will skip already-downloaded files and append to the CSV file.
Connecting to Garmin Connect... Done.
Requesting Login ticket... Done. Ticket=ST-02141344-WEqXaqbVlyOKmWWPqgm4-cas
Authenticating... Done.
Querying list of activities 1..10... Done.
Garmin Connect activity (1/10) [5321283197] San Francisco Running
	2020-08-01T17:56:37+17:00, 01:23:02, 16.428km
[ERROR] Failed to reach url http://connect.garmin.com/proxy/download-service/files/activity/5321283197, error: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/home/pierre/Workspace/garmin-connect-export/gcexport.py", line 1007, in <module>
    main(sys.argv)
  File "/home/pierre/Workspace/garmin-connect-export/gcexport.py", line 988, in main
    actvty['startTimeLocal'])
  File "/home/pierre/Workspace/garmin-connect-export/gcexport.py", line 720, in export_data_file
    raise Exception('Failed. Got an HTTP error ' + str(ex.code) + ' for ' + download_url)
Exception: Failed. Got an HTTP error 400 for http://connect.garmin.com/proxy/download-service/files/activity/5321283197
```
Was wondering if someone has encountered this issue? Wondering if the API changed or if it's related to the ransomware problem where Garmin might have changed something?

I'm on ubuntu 18.04.

**Comment by matmuc** [comment]
Same Error when "download original" by website. So it seems to be a general bug, not related to this script..

**Comment by telemaxx** [comment]
https://connect.garmin.com/status/

**Comment by telemaxx** [comment]
"Uploads and viewing details is working. Exporting from the web Activity Details page is not working"

**Comment by telemaxx** [comment]
it seems ok now,  i just run the script.

**Comment by pierretamisier** [comment]
Agreed, it works today!
